### ISSUE TITLE
Why did we revert to plain Alembic?

### ISSUE THREAD

**Issue by TylerTaylor** [learn-co-curriculum/python-p4-validation-flask-sqlalchemy-validations-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/211188?module_item_id=486871

### Concern

We've been using Flask-SQLAlchemy for the last several labs, but this one has reverted back to plain SQLAlchemy / Alembic. This will likely cause confusion.

### Additional Context

This + [Matt's issue](https://github.com/learn-co-curriculum/python-p4-validation-flask-sqlalchemy-validations-lab/issues/1) make the lab feel incomplete / broken.

**Comment by professor-ben** [comment]
There was some asynchronous development here that resulted in this inconsistency. This module is currently being modified to use Flask-SQLAlchemy and Flask-Migrate.
