### ISSUE TITLE
Opening directions

### ISSUE THREAD

**Issue by abbyesmith** [learn-co-curriculum/python-p4-validation-flask-sqlalchemy-validations-lab#3]
### Canvas Link

https://learning.flatironschool.com/courses/6267/assignments/236260?module_item_id=554247

### Concern

I am running the opening directions as they are written and get errors about `sqlalchemy.exc.ArgumentError: Mapper Mapper[Author(author)] could not assemble any primary key columns for mapped table 'author'

**Comment by sbasken** [comment]
I had the same issue. I added table names and the id as primary key for Author and Post in Models.py, ran `flask db revision --autogenerate -m "<your comment>"` before running `flask db upgrade`  in the terminal and was able to set up the tables.

**Comment by pgill97** [comment]
Added boilerplate code to models and instructions on how to create revision.
